version: '3.8'

services:
  youtube-downloader:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - RATE_LIMIT=10
      - DOWNLOAD_TIMEOUT=300
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
    volumes:
      # Optional: Mount a volume for temporary files if needed
      - /tmp:/tmp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
